export const componentRoutes = [
    {id: 'accordion', label: 'Accordion 手风琴'},
    {id: 'actionSheet', label: 'ActionSheet 上拉菜单'},
    {id: 'alert', label: 'Alert 提示框'},
    {id: 'anchorList', label: 'AnchorList 锚点列表'},
    {id: 'autocomplete', label: 'Autocomplete 自动填充'},
    {id: 'avatar', label: 'Avatar 头像'},
    {id: 'badge', label: 'Badge 角标'},
    {id: 'bottomNavigation', label: 'BottomNavigation 底部导航'},
    {id: 'breadcrumb', label: 'Breadcrumb 面包屑'},
    {id: 'bubbleConfirm', label: 'BubbleConfirm 气泡确认框'},
    {id: 'button', label: 'Button 按钮'},
    {id: 'card', label: 'Card 卡片'},
    {id: 'cascade', label: 'Cascade 级联选择器'},
    {id: 'checkbox', label: 'Checkbox 选择框'},
    {id: 'colorPicker', label: 'ColorPicker 颜色选择'},
    {id: 'contextMenu', label: 'ContextMenu 右键菜单'},
    {id: 'counter', label: 'Counter 数量输入框'},
    {id: 'dataGrid', label: 'DataGrid 数据表格'},
    {id: 'dateTimePicker', label: 'DateTimePicker 日期时间选择器'},
    {id: 'dateTimeRangePicker', label: 'DateTimeRangePicker 日期时间范围选择器'},
    {id: 'descriptions', label: 'Descriptions 描述列表'},
    {id: 'dialog', label: 'Dialog 对话框'},
    {id: 'divider', label: 'Divider 分隔线'},
    {id: 'drawer', label: 'Drawer 抽屉'},
    {id: 'flex', label: 'Flex 弹性布局'},
    {id: 'form', label: 'Form 表单'},
    {id: 'formDialog', label: 'FormDialog 表单对话框'},
    {id: 'grid', label: 'Grid 网格布局'},
    {id: 'highlight', label: 'Highlight 高亮文本'},
    {id: 'image', label: 'Image 图片'},
    {id: 'input', label: 'Input 输入框'},
    {id: 'loading', label: 'Loading 加载中'},
    {id: 'menu', label: 'Menu 菜单'},
    {id: 'pagination', label: 'Pagination 分页器'},
    {id: 'pickerDialog', label: 'PickerDialog 选择对话框'},
    {id: 'placeholder', label: 'Placeholder 占位符'},
    {id: 'progress', label: 'Progress 进度条'},
    {id: 'radio', label: 'Radio 单选框'},
    {id: 'rating', label: 'Rating 评分'},
    {id: 'resizable', label: 'Resizable 尺寸调整'},
    {id: 'scrollbar', label: 'Scrollbar 滚动条'},
    {id: 'segmented', label: 'Segmented 段落选择器'},
    {id: 'select', label: 'Select 选择器'},
    {id: 'skeleton', label: 'Skeleton 骨架屏'},
    {id: 'slidableActions', label: 'SlidableActions 滑动操作'},
]

export const componentRoutesMap = Map.groupBy(componentRoutes, route => route.id)

export const categorizedComponents: [string, string[]][] = [
    ['输入', ['autocomplete', 'button', 'cascade', 'checkbox', 'colorPicker', 'counter', 'dateTimePicker', 'dateTimeRangePicker', 'form', 'formDialog', 'input', 'pickerDialog', 'radio', 'rating', 'segmented', 'select']],
    ['展示', ['accordion', 'avatar', 'badge', 'dataGrid', 'descriptions', 'divider', 'highlight', 'image', 'placeholder']],
    ['反馈', ['actionSheet', 'alert', 'bubbleConfirm', 'contextMenu', 'dialog', 'drawer', 'loading', 'progress']],
    ['导航', ['anchorList', 'bottomNavigation', 'breadcrumb', 'menu', 'pagination']],
    ['布局', ['card', 'flex', 'grid', 'resizable', 'skeleton']],
    ['其他', ['scrollbar', 'slidableActions']]
]